//! Tab ownership and lifecycle.
//!
//! Each `Tab` owns the full PTY ↔ terminal pipeline: a `Term<EventProxy>`
//! wrapped in `Arc<FairMutex>`, the reader thread that feeds PTY output
//! through VTE, and the `Notifier` that delivers keyboard input to the PTY.
//!
//! Supporting types: `TabId` (unique identity), `TermEvent` (winit user
//! event), `EventProxy` (terminal → winit bridge), `Notifier` (input →
//! PTY bridge).

use std::io;
use std::sync::Arc;
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::mpsc;
use std::thread::JoinHandle;
use std::time::{Duration, Instant};

use winit::event_loop::EventLoopProxy;

use oriterm_core::{Event, EventListener, FairMutex, Selection, SelectionPoint, Term};

use crate::pty::{Msg, PtyConfig, PtyEventLoop, PtyHandle, spawn_pty};

/// Unique identifier for a tab.
///
/// Generated by an atomic counter so IDs are unique within a process.
/// The inner value is opaque — callers should not rely on ordering or gaps.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct TabId(u64);

impl TabId {
    /// Generate the next unique tab ID.
    ///
    /// Thread-safe. IDs are monotonically increasing but may have gaps
    /// if tabs are created concurrently.
    pub fn next() -> Self {
        static COUNTER: AtomicU64 = AtomicU64::new(0);
        Self(COUNTER.fetch_add(1, Ordering::Relaxed))
    }
}

/// Events sent from background threads to the winit event loop.
///
/// The PTY reader thread and child-watcher thread produce these.
/// The event loop dispatches them to the appropriate tab handler.
#[derive(Debug)]
pub enum TermEvent {
    /// A terminal state-machine event from the PTY reader thread.
    ///
    /// Wraps `oriterm_core::Event` with the originating tab's identity
    /// so the event loop knows which tab to update.
    Terminal {
        /// Which tab produced this event.
        #[allow(dead_code, reason = "tab routing in Section 15")]
        tab_id: TabId,
        /// The terminal event (wakeup, title change, bell, etc.).
        event: Event,
    },
}

/// Bridges terminal events to the winit event loop.
///
/// Created per-tab. The PTY reader thread calls
/// [`EventListener::send_event`] on this to wake the main thread.
/// Send errors are silently ignored (the window may have closed).
pub struct EventProxy {
    /// Winit's thread-safe event sender.
    proxy: EventLoopProxy<TermEvent>,
    /// Which tab this proxy belongs to.
    tab_id: TabId,
}

impl EventProxy {
    /// Create a new event proxy for the given tab.
    pub fn new(proxy: EventLoopProxy<TermEvent>, tab_id: TabId) -> Self {
        Self { proxy, tab_id }
    }
}

impl EventListener for EventProxy {
    fn send_event(&self, event: Event) {
        let _ = self.proxy.send_event(TermEvent::Terminal {
            tab_id: self.tab_id,
            event,
        });
    }
}

/// Sends input to the PTY and commands to the reader thread.
///
/// Input bytes are written directly to the PTY pipe (avoiding the channel
/// deadlock where the reader thread blocks on `read()` and never drains
/// `Msg::Input`). Resize and shutdown commands still go through the channel.
pub struct Notifier {
    /// Direct PTY writer — bypasses the reader thread's command channel.
    writer: std::sync::Mutex<Box<dyn io::Write + Send>>,
    /// Channel sender for commands (resize, shutdown) to the reader thread.
    tx: mpsc::Sender<Msg>,
}

impl Notifier {
    /// Create a new notifier with a direct PTY writer and command channel.
    pub fn new(writer: Box<dyn io::Write + Send>, tx: mpsc::Sender<Msg>) -> Self {
        Self {
            writer: std::sync::Mutex::new(writer),
            tx,
        }
    }

    /// Send raw bytes to the PTY (keyboard input, escape responses).
    ///
    /// Writes directly to the PTY pipe — no channel hop, no deadlock.
    pub fn notify(&self, bytes: &[u8]) {
        if bytes.is_empty() {
            return;
        }
        if let Ok(mut w) = self.writer.lock() {
            if let Err(e) = w.write_all(bytes) {
                log::warn!("PTY write failed: {e}");
            }
            let _ = w.flush();
        }
    }

    /// Resize the PTY and terminal grid.
    pub fn resize(&self, rows: u16, cols: u16) {
        let _ = self.tx.send(Msg::Resize { rows, cols });
    }

    /// Request the reader thread to shut down.
    pub fn shutdown(&self) {
        let _ = self.tx.send(Msg::Shutdown);
    }
}

/// Maximum time to wait for the reader thread during [`Tab::drop`].
const SHUTDOWN_TIMEOUT: Duration = Duration::from_secs(2);

/// Poll interval while waiting for the reader thread to finish.
const SHUTDOWN_POLL_INTERVAL: Duration = Duration::from_millis(10);

/// Owns all per-tab state: terminal, PTY handles, reader thread.
///
/// Created via [`Tab::new`], which spawns a PTY process and wires the
/// full I/O pipeline. Dropping a `Tab` sends a shutdown signal, kills
/// the child process, and joins the reader thread with a timeout.
pub struct Tab {
    /// Unique tab identifier.
    id: TabId,
    /// Shared terminal state (accessed by both render and PTY threads).
    terminal: Arc<FairMutex<Term<EventProxy>>>,
    /// Sends commands (input, resize, shutdown) to the PTY reader thread.
    notifier: Notifier,
    /// PTY reader thread join handle.
    reader_thread: Option<JoinHandle<()>>,
    /// Spawned PTY (reader/writer/control taken; child remains for lifecycle).
    pty: PtyHandle,
    /// Last known window title (set by OSC 0/2 from the shell).
    title: String,
    /// Bell indicator (set on bell event, cleared on focus).
    has_bell: bool,
    /// Active text selection, if any.
    selection: Option<Selection>,
}

impl Tab {
    /// Spawn a new tab with a live shell process.
    ///
    /// Creates the PTY, terminal state machine, and reader thread. The
    /// terminal is wrapped in `Arc<FairMutex>` for concurrent access by
    /// the render thread and PTY reader thread.
    pub fn new(
        id: TabId,
        rows: u16,
        cols: u16,
        scrollback: usize,
        proxy: EventLoopProxy<TermEvent>,
    ) -> io::Result<Self> {
        // 1. Spawn PTY with the default shell.
        let config = PtyConfig {
            rows,
            cols,
            ..Default::default()
        };
        let mut pty = spawn_pty(&config)?;

        // 2. Take handles before they're moved into the event loop.
        let reader = pty
            .take_reader()
            .ok_or_else(|| io::Error::other("PTY reader unavailable"))?;
        let writer = pty
            .take_writer()
            .ok_or_else(|| io::Error::other("PTY writer unavailable"))?;
        let control = pty
            .take_control()
            .ok_or_else(|| io::Error::other("PTY control unavailable"))?;

        // 3. Create the terminal state machine with an event proxy.
        let theme = crate::platform::theme::system_theme();
        let event_proxy = EventProxy::new(proxy, id);
        let term = Term::new(
            usize::from(rows),
            usize::from(cols),
            scrollback,
            theme,
            event_proxy,
        );
        let terminal = Arc::new(FairMutex::new(term));

        // 4. Wire the message channel. Writer goes to Notifier for direct
        //    PTY writes; the reader thread only needs reader + control.
        let (tx, rx) = mpsc::channel();
        let notifier = Notifier::new(writer, tx);

        // 5. Build and spawn the reader thread.
        let event_loop = PtyEventLoop::new(Arc::clone(&terminal), reader, rx, control);
        let reader_thread = event_loop.spawn()?;

        Ok(Self {
            id,
            terminal,
            notifier,
            reader_thread: Some(reader_thread),
            pty,
            title: String::new(),
            has_bell: false,
            selection: None,
        })
    }

    /// Tab identity.
    #[allow(dead_code, reason = "tab identity used in Section 15")]
    pub fn id(&self) -> TabId {
        self.id
    }

    /// Shared terminal state for rendering.
    ///
    /// The renderer locks the `FairMutex` to snapshot the grid. The lock
    /// is held briefly — the PTY reader thread uses bounded parsing to
    /// avoid starving the renderer.
    pub fn terminal(&self) -> &Arc<FairMutex<Term<EventProxy>>> {
        &self.terminal
    }

    /// Last known window title (from OSC 0/2).
    #[allow(dead_code, reason = "tab bar display in Section 15")]
    pub fn title(&self) -> &str {
        &self.title
    }

    /// Whether the bell has fired since the tab was last focused.
    #[allow(dead_code, reason = "bell indicator in Section 15")]
    pub fn has_bell(&self) -> bool {
        self.has_bell
    }

    /// Clear the bell indicator (call when the tab gains focus).
    #[allow(dead_code, reason = "bell indicator in Section 15")]
    pub fn clear_bell(&mut self) {
        self.has_bell = false;
    }

    /// Set the bell indicator.
    pub fn set_bell(&mut self) {
        self.has_bell = true;
    }

    /// Update the window title.
    pub fn set_title(&mut self, title: String) {
        self.title = title;
    }

    /// Active text selection, if any.
    pub fn selection(&self) -> Option<&Selection> {
        self.selection.as_ref()
    }

    /// Replace the active selection.
    pub fn set_selection(&mut self, selection: Selection) {
        self.selection = Some(selection);
    }

    /// Clear the active selection.
    #[allow(
        dead_code,
        reason = "used by copy operations, keyboard escape, context menu"
    )]
    pub fn clear_selection(&mut self) {
        self.selection = None;
    }

    /// Update the endpoint of an active selection during drag.
    ///
    /// No-op if no selection exists.
    pub fn update_selection_end(&mut self, end: SelectionPoint) {
        if let Some(sel) = &mut self.selection {
            sel.end = end;
        }
    }

    /// Check whether terminal output has invalidated the selection.
    ///
    /// Locks the terminal, checks the `selection_dirty` flag, and clears the
    /// selection if grid content was modified since the last check. Call this
    /// when handling terminal wakeup events.
    pub fn check_selection_invalidation(&mut self) {
        if self.selection.is_none() {
            // No selection to invalidate — still clear the flag to avoid stale state.
            let mut term = self.terminal.lock();
            if term.is_selection_dirty() {
                term.clear_selection_dirty();
            }
            return;
        }
        let mut term = self.terminal.lock();
        if term.is_selection_dirty() {
            term.clear_selection_dirty();
            drop(term);
            self.selection = None;
        }
    }

    /// Send raw bytes to the PTY (keyboard input, escape responses).
    pub fn write_input(&self, bytes: &[u8]) {
        self.notifier.notify(bytes);
    }

    /// Scroll to the live terminal position.
    ///
    /// If the user is viewing scrollback, resets the display offset to zero
    /// so the most recent output is visible. No-op if already at the bottom.
    pub fn scroll_to_bottom(&self) {
        let mut term = self.terminal.lock();
        if term.grid().display_offset() > 0 {
            term.grid_mut().scroll_display(isize::MIN);
        }
    }

    /// Scroll the viewport by `delta` lines (positive = into history).
    ///
    /// Delegates to `Grid::scroll_display`. The grid clamps the offset
    /// to valid bounds, so callers don't need to range-check.
    pub fn scroll_display(&self, delta: isize) {
        self.terminal.lock().grid_mut().scroll_display(delta);
    }

    /// Resize the PTY dimensions.
    ///
    /// Terminal grid resize (reflow) is handled separately in Section 12.
    pub fn resize(&self, rows: u16, cols: u16) {
        self.notifier.resize(rows, cols);
    }
}

impl Drop for Tab {
    fn drop(&mut self) {
        // 1. Signal the reader thread to stop.
        self.notifier.shutdown();

        // 2. Kill the child process to unblock any pending PTY read.
        let _ = self.pty.kill();

        // 3. Join the reader thread with a timeout.
        if let Some(handle) = self.reader_thread.take() {
            let deadline = Instant::now() + SHUTDOWN_TIMEOUT;
            while !handle.is_finished() {
                if Instant::now() >= deadline {
                    log::warn!("tab {:?}: reader thread did not exit within 2s", self.id);
                    break;
                }
                std::thread::sleep(SHUTDOWN_POLL_INTERVAL);
            }
            if handle.is_finished() {
                if let Err(_payload) = handle.join() {
                    log::warn!("tab {:?}: reader thread panicked", self.id);
                }
            }
        }

        // 4. Reap the child process.
        let _ = self.pty.wait();
    }
}

#[cfg(test)]
mod tests;
