//! Key event encoding for terminal input (legacy xterm, Kitty protocol).
//!
//! Converts winit key events into byte sequences understood by terminal
//! applications. The dispatcher chooses between Kitty keyboard protocol
//! (CSI u format) and legacy xterm encoding based on the active terminal mode.

mod kitty;
mod legacy;

use bitflags::bitflags;
use winit::keyboard::{Key, KeyLocation};

use oriterm_core::TermMode;

/// Key event type for Kitty keyboard protocol.
///
/// Legacy encoding only processes `Press` events. Kitty protocol uses all
/// three when `REPORT_EVENT_TYPES` is active.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum KeyEventType {
    /// Initial key press.
    Press,
    /// Held key repeating.
    Repeat,
    /// Key released.
    Release,
}

bitflags! {
    /// Keyboard modifiers for key events.
    ///
    /// Bit layout matches the xterm modifier parameter encoding:
    /// Shift=1, Alt=2, Ctrl=4, Super=8. The parameter sent to the terminal
    /// is `1 + bits` (so Ctrl+Shift = 1 + 1 + 4 = 6).
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
    pub struct Modifiers: u8 {
        /// Shift key held.
        const SHIFT   = 0b0001;
        /// Alt (Meta/Option) key held.
        const ALT     = 0b0010;
        /// Control key held.
        const CONTROL = 0b0100;
        /// Super (Windows/Command) key held.
        const SUPER   = 0b1000;
    }
}

impl Modifiers {
    /// Encode as xterm modifier parameter (`1 + bitmask`).
    ///
    /// Returns 0 when no modifiers are active (caller should omit the parameter).
    pub(crate) fn xterm_param(self) -> u8 {
        if self.is_empty() { 0 } else { self.bits() + 1 }
    }
}

/// Bundled key event for encoding.
///
/// Groups the six parameters of a key event into a single struct to keep
/// the public API clean (avoids clippy `too_many_arguments`).
pub struct KeyInput<'a> {
    /// The logical key identifier (named key or character).
    pub key: &'a Key,
    /// Active modifier keys.
    pub mods: Modifiers,
    /// Current terminal mode flags.
    pub mode: TermMode,
    /// Text generated by the key (from winit, after dead keys/IME).
    pub text: Option<&'a str>,
    /// Physical key location (Standard, Left, Right, Numpad).
    pub location: KeyLocation,
    /// Whether this is a press, repeat, or release event.
    pub event_type: KeyEventType,
}

/// Encode a key event into bytes to send to the PTY.
///
/// Returns an empty `Vec` if the key should not produce output (bare modifier
/// presses, unhandled keys, or suppressed release events).
///
/// Dispatch priority:
/// 1. **Kitty keyboard protocol** — when any `KITTY_KEYBOARD_PROTOCOL` flag is set.
/// 2. **`APP_KEYPAD` numpad** — numpad keys in application keypad mode.
/// 3. **Legacy xterm** — standard VT/xterm escape sequences.
pub fn encode_key(input: &KeyInput<'_>) -> Vec<u8> {
    // Kitty keyboard protocol takes priority when any flag is set.
    if input.mode.intersects(TermMode::KITTY_KEYBOARD_PROTOCOL) {
        return kitty::encode_kitty(input);
    }

    // Legacy mode only sends on press.
    if input.event_type == KeyEventType::Release {
        return Vec::new();
    }

    // `APP_KEYPAD` numpad keys.
    if input.location == KeyLocation::Numpad && input.mode.contains(TermMode::APP_KEYPAD) {
        if let Some(bytes) = legacy::encode_numpad_app(input.key) {
            return bytes;
        }
    }

    legacy::encode_legacy(input.key, input.mods, input.mode, input.text)
}

#[cfg(test)]
mod tests;
