//! Terminal mode flags (DECSET/DECRST, SM/RM).
//!
//! Each flag corresponds to a terminal mode set/reset via escape sequences.
//! The default mode has `SHOW_CURSOR` and `LINE_WRAP` enabled.

use bitflags::bitflags;

bitflags! {
    /// Bitflags for terminal mode state.
    ///
    /// Modes are toggled by DECSET (`CSI ? n h`), DECRST (`CSI ? n l`),
    /// SM (`CSI n h`), and RM (`CSI n l`) escape sequences.
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
    pub struct TermMode: u32 {
        /// DECTCEM — cursor visible.
        const SHOW_CURSOR        = 1;
        /// DECCKM — application cursor keys.
        const APP_CURSOR         = 1 << 1;
        /// DECKPAM/DECKPNM — application keypad mode.
        const APP_KEYPAD         = 1 << 2;
        /// Mode 1000 — report mouse clicks.
        const MOUSE_REPORT_CLICK = 1 << 3;
        /// Mode 1002 — report mouse button + drag.
        const MOUSE_DRAG         = 1 << 4;
        /// Mode 1003 — report all mouse motion.
        const MOUSE_MOTION       = 1 << 5;
        /// Mode 1006 — SGR mouse encoding.
        const MOUSE_SGR          = 1 << 6;
        /// Mode 1005 — UTF-8 mouse encoding.
        const MOUSE_UTF8         = 1 << 7;
        /// Mode 1049 — alternate screen buffer.
        const ALT_SCREEN         = 1 << 8;
        /// DECAWM — auto-wrap at end of line.
        const LINE_WRAP          = 1 << 9;
        /// DECOM — origin mode (cursor relative to scroll region).
        const ORIGIN             = 1 << 10;
        /// IRM — insert mode.
        const INSERT             = 1 << 11;
        /// Mode 1004 — report focus in/out events.
        const FOCUS_IN_OUT       = 1 << 12;
        /// Mode 2004 — bracketed paste mode.
        const BRACKETED_PASTE    = 1 << 13;
        /// Mode 2026 — synchronized output.
        const SYNC_UPDATE        = 1 << 14;
        /// Mode 1042 — urgency hints on bell.
        const URGENCY_HINTS      = 1 << 15;
        /// ATT610 — cursor blinking.
        const CURSOR_BLINKING    = 1 << 16;
        /// LNM — linefeed/new line mode (LF acts as CR+LF).
        const LINE_FEED_NEW_LINE = 1 << 17;

        // Kitty keyboard protocol flags.
        /// Report Esc/alt/ctrl keys using CSI u instead of raw sequences.
        const DISAMBIGUATE_ESC_CODES  = 1 << 18;
        /// Report key press, release, and repeat events.
        const REPORT_EVENT_TYPES      = 1 << 19;
        /// Report shifted key and base layout key.
        const REPORT_ALTERNATE_KEYS   = 1 << 20;
        /// Report every key as an escape sequence.
        const REPORT_ALL_KEYS_AS_ESC  = 1 << 21;
        /// Report the text generated by the key event.
        const REPORT_ASSOCIATED_TEXT  = 1 << 22;
        /// Mode 1007 — alternate scroll (wheel sends arrow keys in alt screen).
        const ALTERNATE_SCROLL       = 1 << 23;
        /// Mode 45 — reverse wraparound (BS wraps to previous line).
        const REVERSE_WRAP           = 1 << 24;
        /// Mode 1015 — URXVT mouse encoding.
        const MOUSE_URXVT            = 1 << 25;

        /// Computed: any mouse reporting mode is active.
        const ANY_MOUSE = Self::MOUSE_REPORT_CLICK.bits()
                        | Self::MOUSE_DRAG.bits()
                        | Self::MOUSE_MOTION.bits();
        /// Computed: any mouse encoding mode is active.
        const ANY_MOUSE_ENCODING = Self::MOUSE_SGR.bits()
                                 | Self::MOUSE_UTF8.bits()
                                 | Self::MOUSE_URXVT.bits();
        /// Computed: all Kitty keyboard protocol flags.
        const KITTY_KEYBOARD_PROTOCOL = Self::DISAMBIGUATE_ESC_CODES.bits()
                                      | Self::REPORT_EVENT_TYPES.bits()
                                      | Self::REPORT_ALTERNATE_KEYS.bits()
                                      | Self::REPORT_ALL_KEYS_AS_ESC.bits()
                                      | Self::REPORT_ASSOCIATED_TEXT.bits();
    }
}

impl Default for TermMode {
    fn default() -> Self {
        Self::SHOW_CURSOR | Self::LINE_WRAP | Self::ALTERNATE_SCROLL
    }
}

impl From<vte::ansi::KeyboardModes> for TermMode {
    fn from(modes: vte::ansi::KeyboardModes) -> Self {
        use vte::ansi::KeyboardModes;

        let mut result = Self::empty();
        result.set(
            Self::DISAMBIGUATE_ESC_CODES,
            modes.contains(KeyboardModes::DISAMBIGUATE_ESC_CODES),
        );
        result.set(
            Self::REPORT_EVENT_TYPES,
            modes.contains(KeyboardModes::REPORT_EVENT_TYPES),
        );
        result.set(
            Self::REPORT_ALTERNATE_KEYS,
            modes.contains(KeyboardModes::REPORT_ALTERNATE_KEYS),
        );
        result.set(
            Self::REPORT_ALL_KEYS_AS_ESC,
            modes.contains(KeyboardModes::REPORT_ALL_KEYS_AS_ESC),
        );
        result.set(
            Self::REPORT_ASSOCIATED_TEXT,
            modes.contains(KeyboardModes::REPORT_ASSOCIATED_TEXT),
        );
        result
    }
}

#[cfg(test)]
mod tests;
