//! Input event types for widget-level event routing.
//!
//! These are widget-oriented events, distinct from platform events (winit).
//! The application layer translates platform events into these types before
//! routing them through the widget tree.

use crate::geometry::Point;

/// Mouse button identity.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum MouseButton {
    /// Primary (usually left) button.
    Left,
    /// Secondary (usually right) button.
    Right,
    /// Middle (wheel) button.
    Middle,
}

/// Keyboard modifier flags stored as a bitmask.
#[derive(Clone, Copy, PartialEq, Eq, Hash, Default)]
pub struct Modifiers(u8);

impl Modifiers {
    /// No modifiers pressed.
    pub const NONE: Self = Self(0);

    const SHIFT: u8 = 1;
    const CTRL: u8 = 2;
    const ALT: u8 = 4;
    const LOGO: u8 = 8;

    /// Modifier with only Shift set.
    pub const SHIFT_ONLY: Self = Self(Self::SHIFT);

    /// Modifier with only Ctrl set.
    pub const CTRL_ONLY: Self = Self(Self::CTRL);

    /// Modifier with only Alt set.
    pub const ALT_ONLY: Self = Self(Self::ALT);

    /// Modifier with only Logo/Super set.
    pub const LOGO_ONLY: Self = Self(Self::LOGO);

    /// Combines this modifier set with another (bitwise OR).
    #[must_use]
    pub const fn union(self, other: Self) -> Self {
        Self(self.0 | other.0)
    }

    /// Returns `true` if Shift is held.
    pub const fn shift(self) -> bool {
        self.0 & Self::SHIFT != 0
    }

    /// Returns `true` if Ctrl is held.
    pub const fn ctrl(self) -> bool {
        self.0 & Self::CTRL != 0
    }

    /// Returns `true` if Alt/Option is held.
    pub const fn alt(self) -> bool {
        self.0 & Self::ALT != 0
    }

    /// Returns `true` if Super/Win/Cmd is held.
    pub const fn logo(self) -> bool {
        self.0 & Self::LOGO != 0
    }
}

impl std::fmt::Debug for Modifiers {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Modifiers")
            .field("shift", &self.shift())
            .field("ctrl", &self.ctrl())
            .field("alt", &self.alt())
            .field("logo", &self.logo())
            .finish()
    }
}

/// Scroll delta in pixels or lines.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum ScrollDelta {
    /// Delta in pixels (trackpad).
    Pixels { x: f32, y: f32 },
    /// Delta in lines (mouse wheel).
    Lines { x: f32, y: f32 },
}

/// What kind of mouse event occurred.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum MouseEventKind {
    /// Button pressed.
    Down(MouseButton),
    /// Button released.
    Up(MouseButton),
    /// Cursor moved.
    Move,
    /// Scroll wheel or trackpad scroll.
    Scroll(ScrollDelta),
}

/// A mouse event in widget-local coordinates.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct MouseEvent {
    /// What happened.
    pub kind: MouseEventKind,
    /// Cursor position in widget-local coordinates.
    pub pos: Point,
    /// Active keyboard modifiers.
    pub modifiers: Modifiers,
}

/// A synthetic hover event generated by the routing layer.
///
/// Not dispatched by the user — the `InputState` generates these
/// automatically when the hovered widget changes.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum HoverEvent {
    /// Cursor entered this widget's bounds.
    Enter,
    /// Cursor left this widget's bounds.
    Leave,
}

/// How a widget responded to an event.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EventResponse {
    /// The widget consumed the event; stop propagation.
    Handled,
    /// The widget did not consume the event; propagate to parent.
    Ignored,
    /// The widget wants keyboard focus.
    RequestFocus,
    /// The widget needs a redraw (state changed visually).
    RequestRedraw,
}

impl EventResponse {
    /// Returns `true` if the event was consumed.
    pub fn is_handled(self) -> bool {
        matches!(
            self,
            Self::Handled | Self::RequestFocus | Self::RequestRedraw
        )
    }
}
